apiVersion: skaffold/v4beta13
kind: Config
build:
  cluster: {}
  tagPolicy:
    sha256: {}
  artifacts:
    - image: my-image
      kaniko:
        dockerfile: Dockerfile
        target: dev

manifests:
  rawYaml:
    - k8s/*
