apiVersion: skaffold/v4beta13
kind: Config
build:
  cluster: {}
  tagPolicy:
    sha256: {}
  artifacts:
    - image: junoinnovations/artifacts
      kaniko:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - k8s/*
